name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: Enable crossBuild
        run: docker run --privileged --rm tonistiigi/binfmt --install all && docker buildx create --use --name multi-arch-builder

      - name: Set up graalvm JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'

      - name: Install cURL Headers
        run: sudo apt update && sudo apt install libcurl4-openssl-dev tree -y

      - name: Build with Gradle
        shell: bash
        run: |
          ./gradlew github
      - name: graalvm build
        run: |
          native-image -jar build/libs/$(ls build/libs -lah | grep .jar | awk '{print $9}') -o build/libs/$(ls build/libs -lah | grep .jar | awk '{print $9}' | sed 's/cf-ddns-jvm/cf-ddns-graalvm-linux-x64/g;s/\.jar$//') --no-fallback
      - name: Print files
        run: |
          tree -hs
