name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: Set up graalvm JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'

      - name: Build with Gradle
        shell: bash
        run: |
          ./gradlew nativeCompile
      - name: Print files
        run: |
          tree -hs
