name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: Enable crossBuild
        run: docker run --privileged --rm tonistiigi/binfmt --install all && docker buildx create --use --name multi-arch-builder

      - name: Set up graalvm JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'

      - name: Install cURL Headers
        run: sudo apt update && sudo apt install libcurl4-openssl-dev tree -y

      - name: graalvm native build
        run: |
          cd graalvm-build && ./gradlew nativeCompile

      - name: Build with Gradle
        shell: bash
        run: |
          ./gradlew github

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            ./build/release1/*
          args: -q

      - name: Print files
        run: |
          tree -hs
