name: auto-release

on:
  push:
    tags:
      - '*-SNAPSHOT'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: multPackage

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*-SNAPSHOT.jar,README.md,build/bin/linuxX64/releaseExecutable/*-SNAPSHOT.kexe"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
