name: snapshot-publish

on:
  push:
    tags:
      - '*-SNAPSHOT'

jobs:
  run-build-on-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: enable crossBuild
        run: docker run --privileged --rm tonistiigi/binfmt --install all && docker buildx create --use --name multi-arch-builder

      - name: Set up graalvm JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'

      - name: Install cURL Headers
        run: sudo apt update && sudo apt install libcurl4-openssl-dev tree -y

      - name: docker login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: release with Gradle
        shell: bash
        run: | 
          ./gradlew -Prelease="true" github

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            ./build/release1/*
          args: -q

      - uses: ncipollo/release-action@v1
        name: release files
        with:
          artifacts: "build/libs/*.jar,README.MD,build/release1/cf-ddns*"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allowUpdates: true

  run-graalvm-build-on-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: Set up graalvm JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'

      - name: graalvm native build
        run: |
          cd graalvm-build && ./gradlew nativeCompileAndCopy

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            ./build/release1/*
          args: -q

      - uses: ncipollo/release-action@v1
        name: release files
        with:
          artifacts: "build/release1/cf-ddns*"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allowUpdates: true

  run-graalvm-build-on-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: Set up graalvm JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'

      - name: graalvm native build
        run: |
          cd graalvm-build && ./gradlew nativeCompileAndCopy

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            ./build/release1/*
          args: -q

      - uses: ncipollo/release-action@v1
        name: release files
        with:
          artifacts: "build/release1/cf-ddns*"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allowUpdates: true

  run-graalvm-docker-build-on-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: enable crossBuild
        run: docker run --privileged --rm tonistiigi/binfmt --install all && docker buildx create --use --name multi-arch-builder

      - name: docker login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: run graalvm native docker build
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t selcarpa/cloudflare-ddns-graalvm-native -f graalvm-build/docker-build/Dockerfile . --push
