name: snapshot-publish

on:
  push:
    tags:
      - '*-SNAPSHOT'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install cURL Headers
        run: sudo apt update && sudo apt install libcurl4-openssl-dev

      - name: Execute with Gradle
        env:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
        run: bash gradlew publish-github

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*-SNAPSHOT.jar,README.md,build/bin/linuxX64/releaseExecutable/*-SNAPSHOT.kexe,build/bin/mingwX64/releaseExecutable/*-SNAPSHOT.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
